############################################################################   
############################################################################
### Description:    Configuration file of the project: "Automated Trauma
###                 Detection in Genocide Court Transcripts"
### Author:         Isaac Misael Olguín Nolasco
### January 2023, TUM
############################################################################
############################################################################
general_set_up:
    dataset_filename: "20230207_Dataset_GTC_FINAL_Witnesses.xlsx" #"20230131_DatasetWitness.xlsx"
    input_dir_name: "input"
    output_dir_name: "output"
    dataset_dir_name: "dataset"
    logs_dir_name: "logs"
    models_dir_name: "models"
    plots_dir_name: "plots"
    
dataset:
    index_columns_dataset: 1
    list_columns_names: ["tribunal", "id_transcript", "case", "accused", "date", "text", "trauma", "role", "witnesses", "n_witnesses", "start", "id_annotation", "id_document"] #["id_document", "id_annotation", "start", "text", "role", "trauma", "court"] 
    col_of_interest_binary_classif: "trauma"
    col_of_interest_multi_label_classif: "role"
    col_of_reference_binary_classif: "text"
    col_of_reference_multi_label_classif: "text"

models: 
    bert: ["bert-base-uncased", "nlpaueb/legal-bert-base-uncased"]
    other: ["snowood1/ConfliBERT-scr-uncased", "GroNLP/hateBERT"]

training_model:
    model_name: "bert-base-uncased"
    epochs: 3
    batch_size: 8
    embedding_size: 512
    return_attention_mask: True
    cross_validation: False
    save_model: False
    store_statistics: False
    test_model: True
    add_special_tokes: True
    max_length: 512
    pad_to_max_length: True
    run_in_gpu: True
    classification_task: "binary"    # [binary|multi]
    learning_rate: 2e-5

active_training:
    size_splits_dataset: 5
    classification_task: "binary"    # [binary|multi]