google_drive_friendly: True
    
general_set_up:
    dataset_filename: "20230112_Dataset_W_Batch1.xlsx" #"Dataset.xlsx"
    input_dir_name: "input"
    output_dir_name: "output"
    dataset_dir_name: "dataset"
    logs_dir_name: "logs"
    models_dir_name: "models"
    
dataset:
    index_columns_dataset: 0
    list_columns_names: ["id_document", "id_annotation", "start", "span", "role", "trauma", "court", "Comments1", "Comments2"] #["id_document", "id_annotation", "span", "role", "trauma", "court"]
    col_of_interest_binary_classif: "trauma"
    col_of_interest_multi_label_classif: "role"
    col_of_reference_binary_classif: "span"
    col_of_reference_multi_label_classif: "span"

training_model:
    epochs: 3
    batch_size: 8
    embedding_size: 512
    return_attention_mask: True
    cross_validation: True
    save_model: False
    store_statistics: True
    test_model: False
    add_special_tokes: True
    max_length: 512
    pad_to_max_length: True
    run_in_gpu: True
    classification_task: "binary"    # [binary|multi]

active_training:
    size_splits_dataset: 10
    classification_task: "binary"    # [binary|multi]